### ISSUE TITLE
Rainbow gem/lint causing problems in heroku deploy, remote migrations...

### ISSUE THREAD

**Issue by mphprogrammer** [department-of-veterans-affairs/roadrunner-rails#40]
```
$ git push heroku master
Counting objects: 17, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (16/16), done.
Writing objects: 100% (17/17), 1.63 KiB | 0 bytes/s, done.
Total 17 (delta 9), reused 0 (delta 0)
remote: Compressing source files... done.
remote: Building source:
remote:
remote: -----> Using set buildpack heroku/ruby
remote: -----> Ruby app detected
remote: -----> Compiling Ruby/Rails
remote: -----> Using Ruby version: ruby-2.3.0
remote: -----> Installing dependencies using bundler 1.9.7
remote:        Running: bundle install --without development:test --path vendor/bundle --binstubs vendor/bundle/bin -j4 --deployment
remote:        Using rake 10.5.0
remote:        Using json 1.8.3
remote:        Using minitest 5.8.4
remote:        Using thread_safe 0.3.5
remote:        Using i18n 0.7.0
remote:        Using builder 3.2.2
remote:        Using erubis 2.7.0
remote:        Using mini_portile2 2.0.0
remote:        Using rack 1.6.4
remote:        Using mime-types 2.99
remote:        Using arel 6.0.3
remote:        Using bcrypt 3.1.10
remote:        Using cancancan 1.13.1
remote:        Using concurrent-ruby 1.0.0
remote:        Using orm_adapter 0.5.0
remote:        Using thor 0.19.1
remote:        Using execjs 2.6.0
remote:        Using multi_json 1.11.2
remote:        Using pg 0.18.4
remote:        Using puma 2.16.0
remote:        Using bundler 1.9.7
remote:        Using rails_serve_static_assets 0.0.5
remote:        Using rails_stdout_logging 0.0.4
remote:        Using rdoc 4.2.1
remote:        Using sass 3.4.21
remote:        Using tilt 2.0.2
remote:        Using tzinfo 1.2.2
remote:        Using nokogiri 1.6.7.2
remote:        Using mail 2.6.3
remote:        Using uglifier 2.7.2
remote:        Using rails_12factor 0.0.3
remote:        Using rack-test 0.6.3
remote:        Using warden 1.2.6
remote:        Using sprockets 3.5.2
remote:        Using sdoc 0.4.1
remote:        Using activesupport 4.2.5.1
remote:        Using loofah 2.0.3
remote:        Using rails-html-sanitizer 1.0.3
remote:        Using rails-deprecated_sanitizer 1.0.3
remote:        Using globalid 0.3.6
remote:        Using activemodel 4.2.5.1
remote:        Using jbuilder 2.4.0
remote:        Using rails-dom-testing 1.0.7
remote:        Using activejob 4.2.5.1
remote:        Using actionview 4.2.5.1
remote:        Using actionpack 4.2.5.1
remote:        Using activerecord 4.2.5.1
remote:        Using actionmailer 4.2.5.1
remote:        Using railties 4.2.5.1
remote:        Using sprockets-rails 3.0.1
remote:        Using responders 2.1.1
remote:        Using jquery-rails 4.1.0
remote:        Using jquery-ui-rails 5.0.5
remote:        Using rails 4.2.5.1
remote:        Using sass-rails 5.0.4
remote:        Using devise 3.5.6
remote:        Bundle complete! 32 Gemfile dependencies, 56 gems now installed.
remote:        Gems in the groups development and test were not installed.
remote:        Bundled gems are installed into ./vendor/bundle.
remote:        Bundle completed (0.34s)
remote:        Cleaning up the bundler cache.
remote:        Could not detect rake tasks
remote:        ensure you can run `$ bundle exec rake -P` against your app with no environment variables present
remote:        and using the production group of your Gemfile.
remote:        rake aborted!
remote:        LoadError: cannot load such file -- rainbow
remote:        /tmp/build_53cb1e226bb3ae43fc6381a56cbefedd/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:274:in `require'
remote:        /tmp/build_53cb1e226bb3ae43fc6381a56cbefedd/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:274:in `block in require'
remote:        /tmp/build_53cb1e226bb3ae43fc6381a56cbefedd/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:240:in `load_dependency'
remote:        /tmp/build_53cb1e226bb3ae43fc6381a56cbefedd/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:274:in `require'
remote:        /tmp/build_53cb1e226bb3ae43fc6381a56cbefedd/lib/tasks/lint.rake:2:in `<top (required)>'
remote:        /tmp/build_53cb1e226bb3ae43fc6381a56cbefedd/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:268:in `load'
remote:        /tmp/build_53cb1e226bb3ae43fc6381a56cbefedd/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:268:in `block in load'
remote:        /tmp/build_53cb1e226bb3ae43fc6381a56cbefedd/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:240:in `load_dependency'
remote:        /tmp/build_53cb1e226bb3ae43fc6381a56cbefedd/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:268:in `load'
remote:        /tmp/build_53cb1e226bb3ae43fc6381a56cbefedd/vendor/bundle/ruby/2.3.0/gems/railties-4.2.5.1/lib/rails/engine.rb:658:in `block in run_tasks_blocks'
remote:        /tmp/build_53cb1e226bb3ae43fc6381a56cbefedd/vendor/bundle/ruby/2.3.0/gems/railties-4.2.5.1/lib/rails/engine.rb:658:in `each'
remote:        /tmp/build_53cb1e226bb3ae43fc6381a56cbefedd/vendor/bundle/ruby/2.3.0/gems/railties-4.2.5.1/lib/rails/engine.rb:658:in `run_tasks_blocks'
remote:        /tmp/build_53cb1e226bb3ae43fc6381a56cbefedd/vendor/bundle/ruby/2.3.0/gems/railties-4.2.5.1/lib/rails/application.rb:452:in `run_tasks_blocks'
remote:        /tmp/build_53cb1e226bb3ae43fc6381a56cbefedd/vendor/bundle/ruby/2.3.0/gems/railties-4.2.5.1/lib/rails/engine.rb:453:in `load_tasks'
remote:        /tmp/build_53cb1e226bb3ae43fc6381a56cbefedd/Rakefile:9:in `<top (required)>'
remote:        /tmp/build_53cb1e226bb3ae43fc6381a56cbefedd/vendor/bundle/ruby/2.3.0/gems/rake-10.5.0/lib/rake/rake_module.rb:28:in `load'
remote:        /tmp/build_53cb1e226bb3ae43fc6381a56cbefedd/vendor/bundle/ruby/2.3.0/gems/rake-10.5.0/lib/rake/rake_module.rb:28:in `load_rakefile'
remote:        /tmp/build_53cb1e226bb3ae43fc6381a56cbefedd/vendor/bundle/ruby/2.3.0/gems/rake-10.5.0/lib/rake/application.rb:689:in `raw_load_rakefile'
remote:        /tmp/build_53cb1e226bb3ae43fc6381a56cbefedd/vendor/bundle/ruby/2.3.0/gems/rake-10.5.0/lib/rake/application.rb:94:in `block in load_rakefile'
remote:        /tmp/build_53cb1e226bb3ae43fc6381a56cbefedd/vendor/bundle/ruby/2.3.0/gems/rake-10.5.0/lib/rake/application.rb:176:in `standard_exception_handling'
remote:        /tmp/build_53cb1e226bb3ae43fc6381a56cbefedd/vendor/bundle/ruby/2.3.0/gems/rake-10.5.0/lib/rake/application.rb:93:in `load_rakefile'
remote:        /tmp/build_53cb1e226bb3ae43fc6381a56cbefedd/vendor/bundle/ruby/2.3.0/gems/rake-10.5.0/lib/rake/application.rb:77:in `block in run'
remote:        /tmp/build_53cb1e226bb3ae43fc6381a56cbefedd/vendor/bundle/ruby/2.3.0/gems/rake-10.5.0/lib/rake/application.rb:176:in `standard_exception_handling'
remote:        /tmp/build_53cb1e226bb3ae43fc6381a56cbefedd/vendor/bundle/ruby/2.3.0/gems/rake-10.5.0/lib/rake/application.rb:75:in `run'
remote:        /tmp/build_53cb1e226bb3ae43fc6381a56cbefedd/vendor/bundle/ruby/2.3.0/gems/rake-10.5.0/bin/rake:33:in `<top (required)>'
remote:        vendor/bundle/bin/rake:16:in `load'
remote:        vendor/bundle/bin/rake:16:in `<main>'
remote:
remote:
...  and so on ...
$ heroku run rake db:migrate
Running rake db:migrate on limitless-shelf-31751... up, run.3476
rake aborted!
LoadError: cannot load such file -- rainbow
/app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:274:in 'require'
/app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:274:in 'block in require'
/app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:240:in 'load_dependency'
/app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:274:in 'require'
/app/lib/tasks/lint.rake:2:in `<top (required)>'
/app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:268:in 'load'
/app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:268:in 'block in load'
/app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:240:in 'load_dependency'
/app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:268:in 'load'
/app/vendor/bundle/ruby/2.3.0/gems/railties-4.2.5.1/lib/rails/engine.rb:658:in `block in run_tasks_blocks'
/app/vendor/bundle/ruby/2.3.0/gems/railties-4.2.5.1/lib/rails/engine.rb:658:in `each'
/app/vendor/bundle/ruby/2.3.0/gems/railties-4.2.5.1/lib/rails/engine.rb:658:in `run_tasks_blocks'
/app/vendor/bundle/ruby/2.3.0/gems/railties-4.2.5.1/lib/rails/application.rb:452:in `run_tasks_blocks'
/app/vendor/bundle/ruby/2.3.0/gems/railties-4.2.5.1/lib/rails/engine.rb:453:in `load_tasks'
/app/Rakefile:9:in `<top (required)>'
(See full trace by running task with —trace)
```

**Comment by mphprogrammer** [comment]
Fixed by removing rainbow gem from development,test groups in Gemfile.
